mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView


urlpatterns = [
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('shop/', include('shopapp.urls')),
    path('req/', include('request_app.urls')),
    path('auth/', include('test_auth.urls')),
    path('api/', include('test_api.urls')),
]

shopapp/urls.py
from django.urls import path, include
from shopapp import views
from rest_framework.routers import DefaultRouter


app_name = 'shopapp'

router = DefaultRouter()
router.register('products', views.ProductViewSet)
router.register('orders', views.OrderViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.ShopIndexView.as_view(), name='index'),
    path('groups/', views.GroupsListView.as_view(), name='group-list'),
    path('products/', views.ProductListView.as_view(), name='products-list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-details'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<int:pk>/confirm-delete/', views.ProductDeleteView.as_view(), name='product-delete'),
    path('products/create/', views.ProductCreateView.as_view(), name='product-create'),
    path('orders/', views.OrderListView.as_view(), name='orders-list'),
    path('orders/create/', views.OrderCreateView.as_view(), name='order-create'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-details'),
    path('orders/<int:pk>/update/', views.OrderUpdateView.as_view(), name='order-update'),
    path('orders/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order-delete'),
]

test_auth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from test_auth import views


app_name = 'test_auth'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(
        template_name='test_auth/login.html',
        redirect_authenticated_user=True
        ), name='login'),
    path('cookie/get/', views.get_cookie_view, name='cookie-get'),
    path('cookie/set/', views.set_cookie_view, name='cookie-set'), 
    path('session/get/', views.get_session_view, name='session-get'), 
    path('session/set/', views.set_session_view, name='session-set'),  
]

shopapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    """
    Модель для представления Товара, который можно продавать в интернет-магазине
    Заказы: :model:'shopapp.Order'
    """
    
    class Meta:
        ordering = ['name', 'price']
        # db_table = 'new_products'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)
    author = models.ForeignKey(to=User, on_delete=models.SET_NULL, blank=True, null=True, related_name='author')

    def __str__(self):
        return f'Товар {self.name},  pk={self.pk}'
    
    @property
    def description_short(self):
        if len(self.description) < 50:
            return self.description
        return self.description[:50] + '...'


class Order(models.Model):
    adress = models.TextField(null=True, blank=True)
    promo = models.CharField(max_length=20, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

shopapp/forms.py
from django import forms
from django.core import validators
from .models import Product, Order
from django.contrib.auth.models import Group


# class ProductForm(forms.Form):
#     name = forms.CharField(label='Название', max_length=100)
#     price = forms.DecimalField(label='Цена', min_value=1, max_value=10000, decimal_places=2)
#     description = forms.CharField(
#         label='Описание товара', 
#         widget=forms.Textarea(attrs={'row': 5, 'cols': 30}),
#         validators=[validators.RegexValidator(
#             regex=r'новый',
#             message='Необходимо слово "новый"'
#         )]
#     )


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'discount']
        labels = {'name': 'Название', 'price': 'Цена', 'description': 'Описание товара', 'discount': 'Скидка'}


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['adress', 'promo', 'user', 'products']
        labels = {'adress': 'Адрес', 'promo': 'Промо-код', 'user': 'Клиент', 'products': 'Товары'}
        widgets = {
            'products': forms.CheckboxSelectMultiple() 
        }


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

shopapp/views.py
"""
В этом файле представления для интернет-магазина: товары, заказы.
"""

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from timeit import default_timer
from django.contrib.auth.models import Group
from shopapp.models import Product, Order
from .forms import ProductForm, OrderForm, GroupForm
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from rest_framework.viewsets import ModelViewSet
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse


@extend_schema(
    description='CRUD представление',
    tags=['Товары'],
    )
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для модели Product
    Полный CRUD для сущности товара
    """

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [SearchFilter, DjangoFilterBackend, OrderingFilter]
    search_fields = ['name', 'description']
    ordering_fields = ['name', 'discount', 'price']
    filterset_fields = ['name', 'description', 'price', 'discount', 'archived', 'author']

    @extend_schema(
        summary='Получение продукта по ID',
        description='Более подробное описание...',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description='Товар не найден, пустой запрос'),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)
    

class OrderViewSet(ModelViewSet):    
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

class ShopIndexView(View):

    def get(self, request):
        products = [
        ('Планшет', 100),
        ('Колонка', 500),
        ('Телефон', 300),
        ]

        context = {
            'time_running': default_timer(),
            'products': products,
        }
        return render(request, 'shopapp/index.html', context=context)


# def shop_index(request):
#     products = [
#         ('Планшет', 100),
#         ('Колонка', 500),
#         ('Телефон', 300),
#     ]

#     context = {
#         'time_running': default_timer(),
#         'products': products,
#     }
#     return render(request, 'shopapp/index.html', context=context)


# def group_list(request):
#     context = {
#         'groups': Group.objects.prefetch_related('permissions').all(),
#     }
#     return render(request, 'shopapp/group-list.html', context=context)


class GroupsListView(View):

    def get(self, request):
        context = {
            'form': GroupForm(),
            'groups': Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/group-list.html', context=context)
    
    def post(self, request):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


# def create_product(request):
#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             # name = form.cleaned_data['name']
#             # price = form.cleaned_data['price']
#             # Product.objects.create(
#             #     name=name,
#             #     price=price
#             # )
#             # Product.objects.create(**form.cleaned_data)
#             form.save()
#             url = reverse('shopapp:products-list')
#             return redirect(url)
#     else:
#         form = ProductForm()
#     context = {
#         'form': form
#     }
#     return render(request, 'shopapp/create_product.html', context=context)


class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price', 'description', 'discount']
    # form_class = ProductForm
    success_url = reverse_lazy('shopapp:products-list')


class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price', 'description', 'discount']
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse('shopapp:product-details', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products-list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


# def products_list(request):
#     context = {
#         'products': Product.objects.all(),
#     }
#     return render(request, 'shopapp/products-list.html', context=context)


class ProductListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    queryset = Product.objects.filter(archived=False)
    context_object_name = 'products'
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['products'] = Product.objects.all()
    #     return context


# class ProductDetailView(View):

#     def get(self, request, pk):
#         # product = Product.objects.get(pk=pk)
#         product = get_object_or_404(Product, pk=pk)
#         context = {
#             'product': product
#         }
#         return render(request, 'shopapp/products-details.html', context=context)


class ProductDetailView(DetailView):
    template_name = 'shopapp/products-details.html'
    model = Product
    context_object_name = 'product'


# def create_order(request):
#     if request.method == 'POST':
#         form = OrderForm(request.POST)
#         if form.is_valid():
#             form.save()
#             url = reverse('shopapp:orders-list')
#             return redirect(url)
#     else:
#         form = OrderForm()
#     context = {
#         'form': form
#     }
#     return render(request, 'shopapp/create_order.html', context=context)

# def orders_list(request):
#     context = {
#         'orders': Order.objects.all(),
#     }
#     return render(request, 'shopapp/orders-list.html', context=context)


class OrderListView(ListView, PermissionRequiredMixin):
    # model = Order
    permission_required = 'shopapp:view_order'
    queryset = Order.objects.all()


class OrderDetailView(DetailView):
    queryset = Order.objects.all()


class OrderCreateView(CreateView):
    form_class = OrderForm
    success_url = reverse_lazy('shopapp:orders-list')
    template_name = 'shopapp/create_order.html'


class OrderUpdateView(UpdateView):
    model = Order
    form_class = OrderForm
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse('shopapp:order-details', kwargs={'pk': self.object.pk})
    

class OrderDeleteView(DeleteView):
    model = Order
    template_name = 'shopapp/order_delete.html'
    success_url = reverse_lazy('shopapp:orders-list')

shopapp/templates/shopapp/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <style>
        .top-menu ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #dddddd;
        }
        .top-menu li {
            float: left;
        }
        .top-menu li a {
            display: block;
            color: rgb(3, 100, 55);
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 20px;
        }
        .top-menu li a:hover {
            background-color: #8f8c8c;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <div class="top-menu">
        <ul>
            <li><a href="{% url 'shopapp:group-list' %}">Группы</a></li>
            <li><a href="{% url 'shopapp:orders-list' %}">Заказы</a></li>
            <li><a href="{% url 'shopapp:products-list' %}">Товары</a></li>
            {% if request.user.is_authenticated %}
                <li style="float:right"><a href="{% url 'test_auth:logout' %}">Выйти</a></li>
                <li style="float:right"><p>Добро пожаловать, {{ request.user.username }}</p></li>
            {% else %}
                <li style="float:right"><a href="{% url 'test_auth:login' %}">Войти</a></li>
            {% endif %}
        </ul>
    </div>
    <!-- Navbar -->
    {% block body %}
        Base body
    {% endblock %}
</body>
</html>

shopapp/templates/shopapp/create_order.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Создание заказа</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Создать</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:orders-list' %}">Обратно к списку заказов</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/create_product.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Создание продукта</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Создать</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:products-list' %}">Обратно к списку товаров</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/group-list.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Группы
{% endblock %}

{% block body %}
    <h1>Группы:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Создать</button>
        </form>
    </div>

    <div>
        {% if not groups %}
            Групп нет
        {% else %}
            <ul>
                {% for group in groups %}
                    <li>
                        {{ group }}
                        <ul>
                            {% for permission in group.permissions.all %}
                                <li>
                                    {{ permission.name }}
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

shopapp/templates/shopapp/index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Index
{% endblock %}

{% block body %}
    <h1>Добро пожаловать на главную страницу нашего магазина!</h1>
{% endblock %}

shopapp/templates/shopapp/order_delete.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Order delete
{% endblock %}

{% block body %}
    <h1>Удаление заказа #{{ object.id }}</h1>
    <h2>Подтверждаете удаление?</h2>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Удалить</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:order-details' pk=object.pk %}">Обратно к заказу</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Заказ #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Заказ {{ object.pk }}</h1>
    <div>
        <div>Заказчик: {{ object.user }}</div>
        <div>Промокод: {{ object.promo }}</div>
        <div>Адрес: {{ object.adress }}</div>
        <p>Товары:</p>
                <ul>   
                    {% for product in object.products.all %}
                        <li>
                            <p>{{ product.name }}</p>
                        </li>
                    {% endfor %}
                </ul> 
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:order-update' pk=order.pk %}">Изменить заказ</a>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:order-delete' pk=order.pk %}">Удалить заказ</a>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:orders-list' %}">Обратно к заказам</a>
    </div>

{% endblock %}

shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Заказы
{% endblock %}

{% block body %}
    <h1>Заказы:</h1>
    <ul>
        {% for order in object_list %}
            <li>
                <p><a href="{% url 'shopapp:order-details' pk=order.pk %}">Заказ #{{ order.id }}</a></p>
                <p>Адрес доставки: {{ order.adress }}</p>
                <p>Промо-код: {{ order.promo }}</p>
                <p>Дата создания: {{ order.created_at }}</p>
                <p>Клиент: {{ order.user }}</p>
                <p>Товары:</p>
                <ul>   
                    {% for product in order.products.all %}
                        <li>
                            <p>{{ product.name }}</p>
                        </li>
                    {% endfor %}
                </ul> 
            </li>
        {% endfor %}
    </ul>

    <div>
        <br>
        <a href="{% url 'shopapp:order-create' %}">Создать заказ</a>
    </div>

{% endblock %}

shopapp/templates/shopapp/order_update.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Update order
{% endblock %}

{% block body %}
    <h1>Изменение заказа</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Изменить</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:order-details' pk=object.pk %}">Обратно к заказу</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Comnfirm delete
{% endblock %}

{% block body %}
    <h1>Удаление продукта {{ object.name }}</h1>
    <h2>Подтверждаете удаление?</h2>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Удалить</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:product-details' pk=object.pk %}">Обратно к товару</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Создание продукта</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Создать</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:products-list' %}">Обратно к списку товаров</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_update.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Изменение продукта</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Изменить</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:product-details' pk=object.pk %}">Обратно к товару</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html'%} 

{% block title %}
    Товар #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Товар {{ product.name }}</h1>
    <div>
        <div>Описание: <em>{{ product.description }}</em></div>
        <div>Цана: {{ product.price }}</div>
        <div>Скидка: {{ product.descount }}</div>
        <div>Архивировано: {{ product.archived }}</div>
    </div>

    {% if perms.shopapp.change_product or product.author == request.user %}
        <div>
            <br>
            <a href="{% url 'shopapp:product-update' pk=product.pk %}">Изменить товар</a>
        </div>
    {% endif %}

    <div>
        <br>
        <a href="{% url 'shopapp:product-delete' pk=product.pk %}">Удалить товар</a>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:products-list' %}">Обратно к товарам</a>
    </div>

{% endblock %}

shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Товары
{% endblock %}

{% block body %}
    <h1>Товары:</h1>
    <div>
        <ul>
            {% for product in products %}
                <li>
                    <p><a href="{% url 'shopapp:product-details' pk=product.pk %}">Название: {{ product.name }}</a></p>
                    <p>Цена: {{ product.price }}</p>
                    <p>Скидка: {{ product.discount }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>

    {% if perms.shopapp.add_product %}
        <div>
            <br>
            <a href="{% url 'shopapp:product-create' %}">Создать товар</a>
        </div>
    {% endif %}

{% endblock %}