mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView


urlpatterns = [
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('shop/', include('shopapp.urls')),
    path('req/', include('request_app.urls')),
    path('auth/', include('test_auth.urls')),
    path('api/', include('test_api.urls')),
]

shopapp/urls.py
from django.urls import path, include
from shopapp import views
from rest_framework.routers import DefaultRouter


app_name = 'shopapp'

router = DefaultRouter()
router.register('products', views.ProductViewSet)
router.register('orders', views.OrderViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.ShopIndexView.as_view(), name='index'),
    path('groups/', views.GroupsListView.as_view(), name='group-list'),
    path('products/', views.ProductListView.as_view(), name='products-list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-details'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<int:pk>/confirm-delete/', views.ProductDeleteView.as_view(), name='product-delete'),
    path('products/create/', views.ProductCreateView.as_view(), name='product-create'),
    path('orders/', views.OrderListView.as_view(), name='orders-list'),
    path('orders/create/', views.OrderCreateView.as_view(), name='order-create'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-details'),
    path('orders/<int:pk>/update/', views.OrderUpdateView.as_view(), name='order-update'),
    path('orders/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order-delete'),
]

test_auth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from test_auth import views


app_name = 'test_auth'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(
        template_name='test_auth/login.html',
        redirect_authenticated_user=True
        ), name='login'),
    path('cookie/get/', views.get_cookie_view, name='cookie-get'),
    path('cookie/set/', views.set_cookie_view, name='cookie-set'), 
    path('session/get/', views.get_session_view, name='session-get'), 
    path('session/set/', views.set_session_view, name='session-set'),  
]

test_auth/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agrement = models.BooleanField(default=False)

test_auth/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from test_auth.models import Profile


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'test_auth/profile.html'


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'test_auth/register.html'
    success_url = reverse_lazy('test_auth:profile')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


def login_view(request): 
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/shop/')
        return render(request, 'test_auth/login.html')
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/shop/')
    return render(request, 'test_auth/login.html', {'error': 'Invalid login credentials!'})


def logout_view(request):
    logout(request)
    return redirect(reverse('test_auth:login'))


class TestLogoutView(LogoutView):
    next_page = reverse_lazy('test_auth:login')


def set_cookie_view(request):
    response = HttpResponse('Cookie set')
    response.set_cookie('new', 'info', max_age=3600)
    return response


def get_cookie_view(request):
    value = request.COOKIES.get('new', 'default info')
    return HttpResponse(f'Cookie value: {value}')


@permission_required('test_auth.view_profile', raise_exception=True)
def set_session_view(request):
    request.session['new'] = 'new info'
    return HttpResponse('Session set')


@login_required
def get_session_view(request):
    value = request.session.get('new', 'default info')
    return HttpResponse(f'Session value: {value}')

test_auth/templates/test_auth/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock %}
</body>
</html>

test_auth/templates/test_auth/login.html
{% extends 'test_auth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

 <!--       {% if error %}
            <p style="color: red">
                {{ error }}
            </p>
        {% endif %}
        <p>
            <label for="username">Ваш ник</label>
            <input type="text" id="username" name="username" required>
        </p>
        <p>
            <label for="password">Пароль</label>
            <input type="password" id="password" name="password" required>
        </p>
-->
        
        {{ form.as_p }}
        <button type="submit">Войти</button>

    </form>
    
    <div>
        <br>
        <a href="{% url 'shopapp:index' %}">На главную</a>
    </div>

{% endblock %}

test_auth/templates/test_auth/profile.html
{% extends 'test_auth/base.html' %}

{% block title %}
    Profile
{% endblock %}

{% block body %}

    <h1>User profile</h1>
    {% if user.is_authenticated %}
        <h2>Детали:</h2>
        <p>Никнейм: {{ user.username }}</p>
        <p>Имя: {{ user.first_name }}</p>
        <p>Фамилия: {{ user.second_name }}</p>
        <p>Почта: {{ user.email }}</p>
        <p>Биография: {{ user.profile.bio }}</p>
    {% else %}
        <h2>User is anonimous</h2>
    {% endif %}

    <div>
        <br>
        <a href="{% url 'shopapp:index' %}">На главную</a>
    </div>

{% endblock %}

test_auth/templates/test_auth/register.html
{% extends 'test_auth/base.html' %}

{% block title %}
    Registration
{% endblock %}

{% block body %}
    <h1>Регистрация</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Регистрация">
    </form>

{% endblock %}